name: Manual Dev Command

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-deps

      - name: Test Project in Development Mode
        run: pnpm dev
