name: Production inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  production:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Send greeting
      run: echo production
  no-env:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo no env
